# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 40b147c6342228e75ab7219f0c1c88dc5d30e2135ee6a80fc05eb804a845a80c1a4fb8c183d976c474f6ca489d918aad3809393601f186c56d094ecd76f0d5e2

test:
  secret_key_base: 7e389c30b10e873bbddb907e2d91ef0a10e98c6f4a604ddc0dde00f5666c72e4a5654a05abc14582bcb190acbb0e873481a164cb6065a4f0788dde4783b23cdb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
